name: Core CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16"
          cache: "npm"
      - run: node -v
      - run: npm -v
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npx turbo build
